java:
  runtime:
    version: 8

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    show:-sql: true
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true


