server:
  port: ${APP_PORT}

spring:
  datasource:
    url: ${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: ${JWK_SET_URI}
    issuer-uri: ${JWT_ISSUER_URI}

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

logging:
  file:
    name: ${LOG_PATH:estimation.log}
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(%M{20}){magenta} %clr(:){faint} %m%n}}'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID} --- [%t] %-40.40logger{39} %M{20} : %m%n}'

keycloak:
  realm: ${KEYCLOAK_REALM}
  server-url: ${KEYCLOAK_URL}

  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}

  username: ${KEYCLOAK_USERNAME}
  password: ${KEYCLOAK_PWD}

  public-client: true

document-path: ${DOC_PATH:}
file-path: ${FILE_PATH:}

